### ISSUE TITLE
2016.10.31-2016.11.01 breakfast

### ISSUE THREAD

**Issue by opst-D-Take** [matsuo-y/git-practice-breakfast#14]
connect matsuo-y/git-practice#12

10/31,11/1の朝ごはんを以下のサイトで公開できる

origin/#{N}-breakfastから作業用(#{N}-breakfast-{acount}-{yyyyMMdd})ブランチをきり、origin/#{N}-breakfastにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の朝食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の朝食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：土井
- branch作成者：郷野
- 開発担当者(朝食報告、2名)：中村、譚
※月をまたぐため、11/1分はbreakfast/201611.htmlとして新しくファイルを作成する
- 検収担当者：松尾
- リリース担当者：姜

ステージング環境： https://staging-git-practice-breakfast.herokuapp.com/breakfast/201610.html
本番環境：　https://matsuo-y.github.io/git-practice-breakfast/breakfast/201610.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-breakfast-pr-{N}.herokuapp.com/
- [x] 中村(10/31分)
- [x] 譚(11/1分)
- [x] 中村(10/31分)
- [x] 譚(11/1分)

**Comment by matsuo-y** [comment]
@jiangheqing 
stagingへのマージが完了したため、リリース作業をお願いします。

**Comment by jiangheqing** [comment]
release完了いたしました。
https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.1
